In [20]:
import csv
from pathlib import Path
import pandas as pd

In [21]:
# File paths
DATA_FOLDER = Path("~/projects/adk_evolutionary_landscape/data/")
msa_dataset_path = DATA_FOLDER / "adk_msa_temp.csv"
ortho_dataset_path = DATA_FOLDER / "adk_ml_dataset.csv"

In [22]:
# Load the main dataset of sequences, organisms, lid-types, and temperatures
msa_dataset = pd.read_csv(msa_dataset_path)
msa_dataset.head()

,Unnamed: 0,org_name,0,1,2,3,4,5,6,7,...,493,494,495,496,497,498,c4_motif,temperature,lid_type,org_in_library
0,0,desulfovibrio_desulfuricans,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,CNCC,31,zinc-like,True
1,1,azorhizobium_caulinodans,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,EA--,30,lidless,True
2,2,methylocella_silvestris,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,EA--,23,lidless,True
3,3,bartonella_henselae,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,EI--,37,lidless,True
4,4,sorangium_cellulosum,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,DS--,28,lidless,True

In [ ]:
msa_sequence_cols = msa_dataset.to_numpy()[:, 0+2:499+2]
msa_sequences = ["".join(r.tolist()).replace("-", "") for r in msa_sequence_cols]
msa_sequences[:5]

['MNILIFGPNGSGKGTQGDLIKQKYNLAHIESGAIFREHIGGGTELGKKAKAYIDRGDLVPDEITIPMVLETLKTKGQHGWLLDGFPRNMVQAEKLWEALQKEGMRLDYVVEILLPRETAKNRIMGRRLCKNNNNHPNNIFIEAIKPNGDVCRVCGGTLSSRSDDQDETAINKRHDIYYNTTDGTLAAAYFFKKLADQGKTKYIELNGEGSIESIKETLLSKLA',
 'MRLVLLGPPGAGKGTQALRLVQRHGIVQLSTGDMLRAAVAAGTPVGLKAKAVMESGGLVSDEIVIGIIAERLDQPDARKGFILDGFPRTVAQADALDKLLADKGLKLDAVIELKVDQAKLLDRILNRAAEAKAKGEPVRKDDDPEVFKTRLEAYNRDTAVVAPYYSARGQLQQIDGMAPIEKVTQAIDSILETA',
 'MRLVFLGPPGAGKGTQSTRLQQKFNIPQLSTGDMLRAAVKAGTPVGLKAKAIMDAGGLVPDEVVVGIIADRIDEPDAKEGFILDGFPRTVKQAEALADILIKKNMKLDAVIELKVDDKALLARIENRAQESLAKGETIRADDNPEAFKKRLESYHAQTAPVSAFYAGKGALKAVDGMAPIDDVSAAIEKALAF',
 'MRIVLLGPPGAGKGTQAKMLCEEYHIPQLSTGDMLREVIRRETEIGKKAKAMINAGTLVSDSIVNQIVSDRIDESDCINGFVLDGYPRTVGQAEVLQQVLQSKNMQLDAVIELIVDEDALLERMKKRVQETIIAGGQVRSDDNPVAFAKRLVEYREKTAPLSEFYLQRRLLKLVDGMIGVTEVSRKIREVLK',
 'MILVLVGPPGAGKGTQAKLLCARFGIPQISTGDMLREAKRSGTLEKRYLDIMDSGGLLPDEAVIGLIARRTVEPDCSNGFLLDGFPRTVPQADALDELLASANQGGKRIDAVIQLDVARPLLEERLIHRRTDKRSGQIYHLVYNPPPPGAELEHRADDRPEAVAKRLDAYEAMTAALLPFYEQKKLLHRVDGVGKPEEVTHRVLSAIGRPGSGGE']

In [41]:
msa_dataset["sequence"] = msa_sequences
msa_dataset = msa_dataset.astype({"sequence": "string"})
for i in range(0, 499):
    if str(i) in msa_dataset.columns:
        del msa_dataset[str(i)]
print(msa_dataset.dtypes)
msa_dataset.head()

Unnamed: 0                 int64
org_name                  object
c4_motif                  object
temperature                int64
lid_type                  object
org_in_library              bool
sequence          string[python]
dtype: object

,Unnamed: 0,org_name,c4_motif,temperature,lid_type,org_in_library,sequence
0,0,desulfovibrio_desulfuricans,CNCC,31,zinc-like,True,MNILIFGPNGSGKGTQGDLIKQKYNLAHIESGAIFREHIGGGTELG...
1,1,azorhizobium_caulinodans,EA--,30,lidless,True,MRLVLLGPPGAGKGTQALRLVQRHGIVQLSTGDMLRAAVAAGTPVG...
2,2,methylocella_silvestris,EA--,23,lidless,True,MRLVFLGPPGAGKGTQSTRLQQKFNIPQLSTGDMLRAAVKAGTPVG...
3,3,bartonella_henselae,EI--,37,lidless,True,MRIVLLGPPGAGKGTQAKMLCEEYHIPQLSTGDMLREVIRRETEIG...
4,4,sorangium_cellulosum,DS--,28,lidless,True,MILVLVGPPGAGKGTQAKLLCARFGIPQISTGDMLREAKRSGTLEK...

In [42]:
# Load the ortholog dataset and add to the corresponding rows in the msa_dataset
ortho_dataset = pd.read_csv(ortho_dataset_path)
ortho_dataset = ortho_dataset.astype({"sequence": "string"})
print(ortho_dataset.dtypes)
ortho_dataset.head()

org_name                object
kcat_mean              float64
Km_mean                float64
kcat_km                float64
log10_kcat             float64
log10_km               float64
log10_kcatkm           float64
sequence        string[python]
temperature              int64
lid_type                object
dtype: object

,org_name,kcat_mean,Km_mean,kcat_km,log10_kcat,log10_km,log10_kcatkm,sequence,temperature,lid_type
0,azorhizobium_caulinodans,20.287820,228.294494,88866.88270,1.307235,2.358495,4.948740,MRLVLLGPPGAGKGTQALRLVQRHGIVQLSTGDMLRAAVAAGTPVG...,30,lidless
1,methylocella_silvestris,123.061061,1066.598980,115377.06590,2.090121,3.028001,5.062119,MRLVFLGPPGAGKGTQSTRLQQKFNIPQLSTGDMLRAAVKAGTPVG...,23,lidless
2,bartonella_henselae,77.856752,342.284019,227462.42120,1.891296,2.534387,5.356910,MRIVLLGPPGAGKGTQAKMLCEEYHIPQLSTGDMLREVIRRETEIG...,37,lidless
3,sorangium_cellulosum,12.518474,216.297684,57876.13408,1.097551,2.335052,4.762500,MILVLVGPPGAGKGTQAKLLCARFGIPQISTGDMLREAKRSGTLEK...,28,lidless
4,elusimicrobium_minutum,138.364545,1725.243090,80200.02874,2.141025,3.236850,4.904175,MIIVLLGAPGAGKGTQSVLVAEKYGLKHISTGDLLREEIANNTELG...,26,zinc-like

In [ ]:
# Turns out there are duplicates that seem okay, the only difference is 1 degree in temperature 
for sequence in ortho_dataset["sequence"].tolist():
    ct = msa_dataset["sequence"].tolist().count(sequence)
    if ct == 0:
        print("Missing sequence:", sequence)
    elif ct > 1:
        print(f"Duplicate sequence ({ct}):", sequence)
        indices = [i for i, x in enumerate(msa_dataset["sequence"].tolist()) if x == sequence]
        for i in indices:
            print(msa_dataset.iloc[i])

Duplicate sequence (2): MTRMLIIGPPGSGKGTQAERISERLGVVAISTGDIFRANVKGETPLGIEAKKYMDNGDFVPDSVTNKMVRDRLSESDVESGFLLDGYPRTTAQVDYLDEILAKNEEKLDVVLQLTADDEELVHRLLGRAKETGRSDDNEAVIRHRLDLYHEQTEAVVAKYAERGILTQVDGIGPIDEVTDRVMQAIKAAQAA
Unnamed: 0                                                        8
org_name                         pseudarthrobacter_chlorophenolicus
c4_motif                                                       ----
temperature                                                      27
lid_type                                                    lidless
org_in_library                                                 True
sequence          MTRMLIIGPPGSGKGTQAERISERLGVVAISTGDIFRANVKGETPL...
Name: 8, dtype: object
Unnamed: 0                                                      563
org_name                                pseudarthrobacter_enclensis
c4_motif                                                       ----
temperature                                                      28
lid_type                                                    lidless
org_in_library                                                False
sequence          MTRMLIIGPPGSGKGTQAERISERLGVVAISTGDIFRANVKGETPL...
Name: 560, dtype: object
Duplicate sequence (2): MRIILLGAPGAGKGTQAQFLMGKYGIPQISTGDMLRAAIKAGTELGLEAKRVMDEGKLVSDEIIIGLVKERIAQDDCKDGFLLDGFPRTIPQADAMKEAGVSVDHCIEFDVPDDVIVERMGGRRVHPASGRVYHVVYNPPKVEGKDNETGDDLIVRDDDKEETVRKRLAIYHEQTKPLVNYYSAEAEAGNCEYHKLDGTRPVEEVSAELAERLG
Unnamed: 0                                                       93
org_name                                   alteromonas_mediterranea
c4_motif                                                       HSDT
temperature                                                      23
lid_type                                                 hbond_like
org_in_library                                                 True
sequence          MRIILLGAPGAGKGTQAQFLMGKYGIPQISTGDMLRAAIKAGTELG...
Name: 92, dtype: object
Unnamed: 0                                                      434
org_name                                      alteromonas_macleodii
c4_motif                                                       HSDT
temperature                                                      23
lid_type                                                 hbond_like
org_in_library                                                False
sequence          MRIILLGAPGAGKGTQAQFLMGKYGIPQISTGDMLRAAIKAGTELG...
Name: 432, dtype: object

In [55]:
# Join on sequence and leave missing ones empty
full_dataset = msa_dataset.join(ortho_dataset.set_index("sequence"), on="sequence", how="left", lsuffix="", rsuffix="_ortho", validate="many_to_one")
for i in range(len(full_dataset)):
    if full_dataset.iloc[i]["lid_type"] != full_dataset.iloc[i]["lid_type_ortho"]:
        print("Mismatch lid type:", full_dataset.iloc[i]["lid_type"], full_dataset.iloc[i]["lid_type_ortho"])
    if full_dataset.iloc[i]["temperature"] != full_dataset.iloc[i]["temperature_ortho"]:
        print("Mismatch temperature:", full_dataset.iloc[i]["temperature"], full_dataset.iloc[i]["temperature_ortho"])
full_dataset = full_dataset.drop(columns=["lid_type_ortho", "temperature_ortho"])
full_dataset.head()

Mismatch lid type: zinc-like nan
Mismatch temperature: 31 nan
Mismatch lid type: lidless nan
Mismatch temperature: 50 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 88 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 60 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 9 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 23 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 46 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 13 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 68 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 73 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 25 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 29 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 26 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 26 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 20 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 25 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 32 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 33 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 34 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 31 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 32 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 31 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 31 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 20 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: lidless nan
Mismatch temperature: 34 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 42 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 20 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 55 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 27 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 27 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 27 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 27 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 33 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 34 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 31 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 35 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 34 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 29 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 31 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 31 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 32 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 29 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 29 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 34 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 45 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 26 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 41 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 25 nan
Mismatch lid type: lidless nan
Mismatch temperature: 11 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 55 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 34 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: other nan
Mismatch temperature: 34 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 34 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: lidless nan
Mismatch temperature: 33 nan
Mismatch lid type: lidless nan
Mismatch temperature: 26 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 32 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 35 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 34 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 34 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 27 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 31 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 32 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 33 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 25 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 25 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 36 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 26 nan
Mismatch lid type: lidless nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 26 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 33 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 55 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 33 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 31 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 27 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 20 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 29 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 36 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 27 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 35 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 25 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 29 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 45 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 57 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 47 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 55 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 55 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 51 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 50 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 50 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 45 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 50 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 50 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 50 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 55 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 26 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 16 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 14 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 31 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 28 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 30 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 33 nan
Mismatch lid type: lidless nan
Mismatch temperature: 30 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 37 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 35 nan
Mismatch lid type: zinc-like nan
Mismatch temperature: 37 nan
Mismatch lid type: lidless nan
Mismatch temperature: 35 nan
Mismatch lid type: hbond_like nan
Mismatch temperature: 28 nan

,Unnamed: 0,org_name,c4_motif,temperature,lid_type,org_in_library,sequence,org_name_ortho,kcat_mean,Km_mean,kcat_km,log10_kcat,log10_km,log10_kcatkm
0,0,desulfovibrio_desulfuricans,CNCC,31,zinc-like,True,MNILIFGPNGSGKGTQGDLIKQKYNLAHIESGAIFREHIGGGTELG...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,azorhizobium_caulinodans,EA--,30,lidless,True,MRLVLLGPPGAGKGTQALRLVQRHGIVQLSTGDMLRAAVAAGTPVG...,azorhizobium_caulinodans,20.287820,228.294494,88866.88270,1.307235,2.358495,4.948740
2,2,methylocella_silvestris,EA--,23,lidless,True,MRLVFLGPPGAGKGTQSTRLQQKFNIPQLSTGDMLRAAVKAGTPVG...,methylocella_silvestris,123.061061,1066.598980,115377.06590,2.090121,3.028001,5.062119
3,3,bartonella_henselae,EI--,37,lidless,True,MRIVLLGPPGAGKGTQAKMLCEEYHIPQLSTGDMLREVIRRETEIG...,bartonella_henselae,77.856752,342.284019,227462.42120,1.891296,2.534387,5.356910
4,4,sorangium_cellulosum,DS--,28,lidless,True,MILVLVGPPGAGKGTQAKLLCARFGIPQISTGDMLREAKRSGTLEK...,sorangium_cellulosum,12.518474,216.297684,57876.13408,1.097551,2.335052,4.762500